### ISSUE TITLE
Invalid JSON (Unexpected " " at position 4 in state STOP) when upgrading to audit-ci 2.2.0

### ISSUE THREAD

**Issue by fernandofleury** [IBM/audit-ci#102]
Hey all 👋 

Due to: https://github.com/IBM/audit-ci/issues/96 I've tried to bump the package version, but now I'm facing 

```
Yarn audit report results:
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: Invalid JSON (Unexpected " " at position 4 in state STOP)
```
(It's visible here: https://travis-ci.org/sumup/circuit-ui/jobs/559411807)

Any ideas on how to proceed? Thanks!

**Comment by quinnturner** [comment]
Hi @fernandofleury, thanks for creating this issue!

This is my first time seeing this behaviour. My interim suggestion would be to rollback to `2.1.0` until we find a fix. Are you able to share the dependencies in `package.json`?

CC: @dw2

**Comment by quinnturner** [comment]
EDIT: https://github.com/sumup/circuit-ui/blob/master/package.json

**Comment by fernandofleury** [comment]
Hey @quinnturner I'm gonna try it out and report how it goes 😃

**Comment by fernandofleury** [comment]
It did work with `2.1.0` 😄 
https://travis-ci.org/sumup/circuit-ui/jobs/559499736
