### ISSUE TITLE
Runs forever, CPU at 145%, when using nodejs v8.15.0

### ISSUE THREAD

**Issue by binarykitchen** [IBM/audit-ci#109]
Yeah, that title says it all. Just 
- run `yarn run audit-ci <whatever>` using nodejs v8.15.0, 
- have a coffee and 
- come back
- Still running and CPU is blocking my system.

Changed to nodejs v10 and 12, works fine there. Happens with audit-ci v1.5.0 and latest v2.3.0 both.

Would be nice to have a verbose mode so that I can see where exactly your audit tool is stuck with.

**Comment by binarykitchen** [comment]
Btw using a private npm registry here and having scoped packages.

**Comment by quinnturner** [comment]
Thanks for the thorough bug report. I agree with having a verbose option. I don't think `yarn` supports having a private repo: https://github.com/yarnpkg/yarn/issues/7012. If this is the case, you can try using `NPM` as the auditer for Node 8.

**Comment by binarykitchen** [comment]
Might be that, dunno know. Still doesn't explain why it works when sticking to yarn while using Node.js v10 instead.

**Comment by quinnturner** [comment]
I haven't heard much from this issue in a while. Unless someone mentions that they have seen this issue in a week (and it's not this issue: #103), I will close this.

(Sorry for late pings)
