### ISSUE TITLE
npm show causing EAUTHUNKNOWN with VSO Package feeds

### ISSUE THREAD

**Issue by Lokiem** [IBM/audit-ci#117]
Hey, I realise that this is likely a limitation / bug within VSO's package feed itself and have raised it as an issue over there.

The recent addition of "npm show audit-ci version" in 2.4.2 is causing an authentication issue in Azure DevOps, even with an authenticated token in my projects .npmrc (No issues with npm installs etc, so authentication is working fine).

I don't think there is any way to avoid this other than fixing my version to 2.4.1, or am I missing something here?

**Comment by quinnturner** [comment]
I had no idea this would be a blocking issue for some builds.

The two approaches I would be comfortable moving forward with would be:

1) Somehow fix it by avoiding `npm show audit-ci version` call (potentially by reading the disk).
2) Have a config option to toggle showing the version.

@Lokiem, thoughts?

**Comment by Lokiem** [comment]
The command now miraculously works, I'm sorry for flagging this as a possible issue. (Though I'd tend to favour the QoL default, with a flag to disable. But no fix is required now!)

Whether this was some issue with my setup, or if the raised issue on the VSO boards had someone do a sneaky fix I'll never know.

**Comment by quinnturner** [comment]
Thanks! Feel free to re-open if the issue arises again.
