### ISSUE TITLE
append custom message to the report

### ISSUE THREAD

**Issue by sumanapotturu** [IBM/audit-ci#118]
Summary report gives high level information about why the audit failed and this is great. But a lot of developers looking at it are not sure what to do next and how to fix it. 
It would be great to have an option to append **custom message** to the generated report which points the developers to the resources they need to refer to if audit-ci test failed

**Comment by quinnturner** [comment]
I am definitely open to this idea behind a flag (likely enabled by default). I don't have immediate time to work on this and would be willing to point anyone in the right direction for this 😄

**Comment by quinnturner** [comment]
`audit-ci` is updated to now provide links and significantly more details upon failures. IMO, I think the majority of cases are covered in the current implementation. Accordingly, I am going to close this ticket. Feel free to open it again if the current implementation doesn't suffice!
