### ISSUE TITLE
Carriage return in bin/audit-ci

### ISSUE THREAD

**Issue by cantide5ga** [IBM/audit-ci#13]
I'd open a PR for this, but doesn't appear that the master branch has this issue.

With v1.0.1 on a non-Windows machine, this is the output error: `/usr/bin/env: ‘node\r’: No such file or directory`

Revealed via: `cat -A node_modules/audit-ci/bin/audit-ci`; output:
```
#!/usr/bin/env node^M$
require('../');
```

**Comment by quinnturner** [comment]
Thanks for the issue! I work and deploy from a windows machine, so perhaps this occurs during the NPM publishing process. I will look into this shortly.

**Comment by quinnturner** [comment]
I have published [v1.0.2 to NPM](https://www.npmjs.com/package/audit-ci). I packaged it in a Linux environment. I extracted the package and performed `cat -A bin/audit-ci` and it had just the `$` line-break.

**Comment by cantide5ga** [comment]
Nice turn around - thanks!
