### ISSUE TITLE
audit-ci is generating a huge file that breaks our deploy to firebase

### ISSUE THREAD

**Issue by felipe-augusto** [IBM/audit-ci#135]
After we run:

 ```
yarn audit-ci --moderate
```

On CircleCI (node:10.15.3) we got a huge file named:

```sh
-rw-------   1 circleci circleci 1663508480 Mar 18 19:09 core.786.!usr!local!bin!node
```

This file gets included in the zip file we send to deploy to our cloud functions and we got an error because the zip file is too big. It goes from 350kb to 65 MB in our case.

**Comment by quinnturner** [comment]
Hey @felipe-augusto,

I apologize for not getting back to you earlier! Not sure if you got this resolved. Can you confirm if this is still an issue?

65 MB, if I recall, is roughly the size of Node.js as a whole. Not sure if that's a coincidence or even flat out wrong.

**Comment by quinnturner** [comment]
Closing due to being stale. Feel free to comment if this is still an issue and is directly related to `audit-ci`.
