### ISSUE TITLE
Using pass-enoaudit flag together with report-type: important causing crash in npm-auditer

### ISSUE THREAD

**Issue by Stompf** [IBM/audit-ci#139]
I'm using the audit-ci as a part of my CI/CD pipeline and used the `pass-enoaudit` flag to let me deploy even if the audit system is down. Now this caused a hard to find error that when using the `report-type: important` it will crash with a `TypeError: Cannot convert undefined or null to object` if the npm audit returns a `ENOAUDIT` code.

After looking at the code I guess this is because in the `audit` function in `npm-auditer.js` will call `printReport` if the code is `ENOAUDIT` and then if using `important` it will start to use the `Object.keys(parsedOutput.advisories)` that does not exist thus throwing the error and failing my pipeline.

https://github.com/IBM/audit-ci/blob/4f499081ca58ef78e45dd960814ef4c7f0a6a4a4/lib/npm-auditer.js#L104

My exception how the function would work is that it also takes the `retry-count` into consideration before exiting with a non-error code if the `pass-enoaudit` flag is set when using npm and not trying to print a output with the `printReport` function.

**Comment by quinnturner** [comment]
Thank you for the detailed bug report! I will try and get on a fix tomorrow :)
