### ISSUE TITLE
`--report-type full` always says "Yarn audit report results"

### ISSUE THREAD

**Issue by G-Rath** [IBM/audit-ci#144]
Running `audit-ci --report-type full` results in:

> Yarn audit report JSON:

Regardless of what tool was actually used.

This doesn't happen for any of the other report types, and the "passed" line at the end always has the correct package manager.

Reproduced using latest, against [this repo](https://github.com/G-Rath/terraport)

**Comment by quinnturner** [comment]
Thanks for the heads up! Seems like it was a simple typo:

In `npm-auditer.js`:
```js
printReportObj("Yarn audit report JSON:", parsedOutput);
```

I will fix this typo and release `v3.0.1`.

**Comment by G-Rath** [comment]
Ah I've already got a fix & making a PR :)
