### ISSUE TITLE
Support a config file format that allows for comments

### ISSUE THREAD

**Issue by G-Rath** [IBM/audit-ci#148]
There's a few ways this can be done, but wanted to open an issue to kick off some discussion.

Overall the idea is that it would be useful if a config format that allowed for comments would be supported, since then you could annotate white listings:

```
{
  "path-whitelist": [
    // not patchable at this time
    "1486|laravel-mix>webpack-dev-server>http-proxy-middleware>http-proxy"
  ]
}
```

Personally I'm a fan of JSON5, which has 1 dependency, but people also seem to like YAML for which there is [YAML](https://www.npmjs.com/package/yaml) that has no dependencies (if you're considered about that).

Another possible solution as a middle ground could be to support piping in a config, which would let you do `json5 audit-ci.json | audit-ci`.

Thoughts?

**Comment by quinnturner** [comment]
I am open to having more flexible configuration options.

We currently use `yargs` for managing all configuration.

In `audit-ci.js`:

```js
const { argv } = yargs
  .config("config")
  .options({
    ...options
  });
```

I haven't reviewed Yargs config option in a while, but here's the most recent information on it:

https://github.com/yargs/yargs/blob/master/docs/advanced.md#building-configurable-cli-apps

Relevant information:

> 
> ## .rc files
> 
> It's common for libraries, e.g., Babel, ESLint, to allow you to provide configuration by populating a .rc file.
> 
> Yargs' config(), combined with the module find-up, makes it easy to implement .rc functionality:
> 
> ```js
> const findUp = require('find-up')
> const fs = require('fs')
> const configPath = findUp.sync(['.myapprc', '.myapprc.json'])
> const config = configPath ? JSON.parse(fs.readFileSync(configPath)) : {}
> const argv = require('yargs')
>   .config(config)
>   .argv
> ```

More info on other config-related Yargs documentation: https://github.com/yargs/yargs/blob/master/docs/api.md#config

**Comment by quinnturner** [comment]
Generally speaking, the solution should be backwards compatible with the following functionality:

1. Support JSON files
1. Support arbitrary file names
1. Not break existing handling of arguments and config (honestly, I am not exactly sure what the existing behaviour is if you combine args and config, but whatever it is, it should probably be compatible with that).

Realistically, the "safest" way to support all of this is to pass the proper config object directly into Yargs and let it handle the config options. However, the process of obtaining that config object (reading a JSON file, JSON5 file, piping, YAML, etc.) is flexible.

**Comment by jacobdr** [comment]
Would be great to see a behavior similar to that of Webpack where you can use a JSON or a .js file. Our team struggles to have to lookup the vulnerability numbers when we take a look at the JSON without any comments and we reference a specific numeric in our allowList. The [example|https://github.com/IBM/audit-ci#testnpm-config-fileaudit-cijson] is a little bit unclear if we can make this a `number|string-name-of-package` so it might just be our user error as new-time joiners to this package

**Comment by kmannislands** [comment]
+1 for the JSON 5 comment support idea.

**Comment by quinnturner** [comment]
#197 should do the trick 👍🏻
