### ISSUE TITLE
[BREAKING]: Change whitelist to allowlist & blacklist to denylist

### ISSUE THREAD

**Issue by quinnturner** [IBM/audit-ci#150]
I noticed during a [PR review](https://github.com/microsoft/essex-alpha-build-infra/pull/18) that [Alex.js](https://alexjs.com) suggested the term whitelist and blacklist as potentially being insensitive. I am suggesting to change from `whitelist` to `allowlist`.

I am not wholly sure if this change is desirable. This is primarily a way to start a discussion on the topic.

The migration path would likely be that we support the `whitelist` naming convention for backwards compatibility for a while, potentially forever. However, the docs would update to use the phrasing `allowlist` or `passlist` or `allow-list` or `pass-list`, and `denylist` or `deny-list`.

Note that currently there is no usage of the term `blacklist` in the project, just adding the usage here for consistency.

**Comment by jamesreggio** [comment]
I added #153 as an interim solution.
