### ISSUE TITLE
Support Yarn

### ISSUE THREAD

**Issue by quinnturner** [IBM/audit-ci#16]
[Yarn@1.12.3](https://yarnpkg.com/lang/en/docs/install/) introduced the `yarn audit` command. It functions differently than `npm audit`.

The expected behaviour is to use `yarn audit` and parse the result of the audit. It is not necessarily important to make the `audit-ci` report to look similar to the NPM equivalent report.

The NPM reporter should be separated from the Yarn reporter (issue #5). PR https://github.com/IBM/audit-ci/pull/15 is a sufficient starting point.

**Comment by quinnturner** [comment]
**Suggested specification**

- Support automatically detecting whether the project uses `yarn.lock` or `package-lock.json`
  - This is a **breaking change** since some projects manage both `yarn.lock` and `package-lock.json` and we can't tell which audit to run.
- Should be allowed to specify the type: `--pm yarn`, `--package-manager yarn`, `--pm npm`, `--package-manager npm`; all other values are immediate halting errors. If no value is provided, it will figure it out based on the files it finds in the filesystem.
- It is not expected to have a similar output style as the existing `npm audit`. However, it should provide enough information and look _good enough_ to help consumers make decisions about their package management.

**Comment by quinnturner** [comment]
[Work in progress](https://github.com/quinnturner/audit-ci/tree/feat/yarn)

**Comment by dbartholomae** [comment]
Following. If I can help, please let me know!

**Comment by quinnturner** [comment]
@dbartholomae You're welcome to review the current PR for it https://github.com/IBM/audit-ci/pull/26. It is running correctly locally for me, but another pair of eyes would be great.

I am looking to introduce unit testing along-side this PR. It would be nice to add the tests before the Yarn PR gets merged, but not a requirement.

**Comment by dbartholomae** [comment]
On it :-)
