### ISSUE TITLE
Compatibility with npm-audit-html

### ISSUE THREAD

**Issue by TheDukeDK** [IBM/audit-ci#174]
First, thanks for providing this tool!

It would be great if we could use it in conjunction with npm-audit-html to generate an html report. 

Unfortunately I can see that there is some non JSON output when piped to a file.

![image](https://user-images.githubusercontent.com/8044990/106792968-24c4d780-6657-11eb-9f42-0deb7f0a8c3c.png)

This causes npm-audit-html to fail. If I remove these first two lines I can pipe it to npm-audit-html and it generates an html file fine.

Are these two additional lines needed? If not removing them would make it compatible with npm-audit-html...

**Comment by quinnturner** [comment]
This is a similar request to this: https://github.com/IBM/audit-ci/issues/147

 The audit-ci version is definitely optional. However, it's not as clear how we handle the final output.
 
 I am definitely open to this change!

**Comment by quinnturner** [comment]
I think this was solved with #193. Please re-open if you're experiencing similar issues!
