### ISSUE TITLE
audit-ci fails on nested via links

### ISSUE THREAD

**Issue by p-v-d-Veeken** [IBM/audit-ci#183]
Hi,

audit-ci returns the error: 

```
Cannot create property 'paths' on string 'postcss-preset-env'
Exiting...
```

On the following audit json output: https://pastebin.com/4FKv0d1P

We have traced the error to the following lines of code: https://github.com/IBM/audit-ci/blob/be22cc9b618d62af1b65e77849b571a674826e41/lib/Model.js#L79

The issue being that the code assumes that `via` links are only ever one link deep. While in fact they can be several links long.

**Comment by bensullivan** [comment]
I think I have the same problem:

` $ audit-ci
audit-ci version: 4.0.0
NPM audit report results:
{
  "advisories": {},
  "metadata": {
    "vulnerabilities": {
      "info": 0,
      "low": 0,
      "moderate": 85,
      "high": 11,
      "critical": 0,
      "total": 96
    },
    "dependencies": {
      "prod": 2845,
      "dev": 1,
      "optional": 33,
      "peer": 2,
      "peerOptional": 0,
      "total": 2880
    }
  }
}
Cannot create property 'paths' on string 'chokidar'
Exiting...
`
