### ISSUE TITLE
audit-ci version: 3.2.0 Cannot convert undefined or null to object Exiting...

### ISSUE THREAD

**Issue by autoGlymm** [IBM/audit-ci#189]
there isn't much thant the title 

```
audit-ci version: 3.2.0
Cannot convert undefined or null to object
Exiting...
```

**Comment by quinnturner** [comment]
Hi there,

Are you running `yarn`, `npm6`, or `npm7`? What happens when you run `npm|yarn audit`? Can you post that here?

I am pretty sure that `allowList` should be `allowlist`. Also, consider upgrading to the latest version of audit-ci, `v4.2.0`.

**Comment by autoGlymm** [comment]
down graded my npm version and its back to normal

**Comment by quinnturner** [comment]
You can alternatively upgrade to latest `audit-ci` which supports `NPM 7`
