### ISSUE TITLE
Invalid JSON config file

### ISSUE THREAD

**Issue by klaudiogurraj** [IBM/audit-ci#191]
Hi, I am trying to run the config example file but it doesn't work.
I'm running this command on the root path of the folder which contains my npm project.
`npx audit-ci --config audit-ci.json`

I get an `Invalid JSON config file: audit-ci.json` error. I've tried full path , quotes etc. still getting this error.

The audit-ci.json is simple and lies in the same directory level while running the command.
`{
  "high": true,
  "skip-dev": true
}`

I cannot seem to understand what am I doing wrong? 
running `npx audit-ci -h --skip-dev` runs fine
audit-ci version 4.1.0

I am running the command in Powershell...

**Comment by quinnturner** [comment]
Hi there, thank you for the report!

I was unable to reproduce this issue on my Mac with identical configuration. I am wondering if it's related to Powershell or Windows?

I just tried to use Windows and Unix line endings (`\r\n` and `\n`) on my Mac for a config file and both worked.

Are you able to try Git Bash for Windows?

Sorry that I couldn't be more help! `skip-dev` is a very new feature so there's a chance that something slipped through the cracks, though I couldn't find any glaring issues in a quick code review.

**Comment by klaudiogurraj** [comment]
Hi, thanks for the quick response.
I think I found the problem. I've tried what you said and noticed something.

I've opened the file with Visual Studio Code and somehow changed the coding to UCS-2 LE-BOM from UTF-8 what Notepad++ is configured. I've changed the encoding and now it works.  I believe it only works with UTF-8.

Thank you for your time and the help 👍
