### ISSUE TITLE
Are you open to supporting node v6

### ISSUE THREAD

**Issue by protoEvangelion** [IBM/audit-ci#20]
My [travis ci build](https://travis-ci.org/node-gh/gh/jobs/473111523) is failing for node v6 because of a dangling comma in a function argument.

```bash
0.09s$ if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then audit-ci --moderate; fi
/home/travis/build/node-gh/gh/node_modules/audit-ci/lib/audit-ci-reporter.js:61
      );
      ^
```

This could be solved with a `.prettierrc` file setting:

```json
{
    "trailingComma": "es5"
}
```

Would you be open to accepting a PR for this?

Thanks for your great work on this by the way. It's a fantastic idea!

**Comment by quinnturner** [comment]
Yes, I am open to supporting v6. I am also good with introducing `prettier`! You're welcome to submit a PR for this 😄

**Comment by quinnturner** [comment]
For this to be set to _closed_ it is important to introduce the change in the `Travis-CI` build. I will be creating a PR for this now and reference this issue.

**Comment by quinnturner** [comment]
With the introduction of #21 and #23, we support Node 6.
