### ISSUE TITLE
Expose internals as library for programmatic use

### ISSUE THREAD

**Issue by paambaati** [IBM/audit-ci#212]
At @getoslash, we use a handmade script (https://gist.github.com/paambaati/b7dd99d67f5402b62d7f8ef95ef65e01) to auto-generate yarn resolutions for audit-vi vulnerabilities.

It would be massively useful if the package also exposed some of its internals as an API, so we could avoid shelling to the command itself and instead use `audit-CI` as a library.

**Comment by quinnturner** [comment]
I am planning on supporting this. I think it's going to be possible with my refactor in #226. As a result, the package will also have types!

**Comment by paambaati** [comment]
@quinnturner Thanks for the response! I now see that the PR is merged, but I don’t see updates to the documentation. Is this still open? Or should I dive into the code and I’d see exports for the key audit functions?

**Comment by quinnturner** [comment]
I was probably a bit hasty to say it was supported 😅 I'd like it to be though, and it's not too far off.

Short todo list for me to make this supported:

- need to export functions
- export built TS types
- add docs

I will try to release something this week that adds all of that!

**Comment by quinnturner** [comment]
Hey, I haven't forgotten about this. I've had to spend all my extra time on another professional project which will be done within the week. I will try to tackle this afterwards. Thanks for understanding!

**Comment by quinnturner** [comment]
Support added with this PR #271
