### ISSUE TITLE
No way to get information about the issue

### ISSUE THREAD

**Issue by pladaria** [IBM/audit-ci#215]
For example:
```
Vulnerable advisories are: 1007082
```

Google returns 0 related results for that number.
Also 0 results here: https://github.com/advisories?query=1007082

Would be possible to return a URL to the advisory or something useful?

**Comment by TimoVink** [comment]
Came here to look for a solution for the same problem. Found two things:

1) This URL format will get you to the right place: https://www.npmjs.com/advisories/1007082
2) If you use `--report-type full` the output includes the url tot he relevant GitHub Advisory.

**Comment by pladaria** [comment]
https://www.npmjs.com/advisories/1007082 returns a 404 page

I like the short report, so my feature request would be to show the github links instead of the npm issue numbers

**Comment by quinnturner** [comment]
This should be resolved with an expansion of #217 to link to the GitHub advisory database, like: https://github.com/advisories/GHSA-gmv4-r438-p67f

**Comment by quinnturner** [comment]
Closing in #230, with a handy URL for the advisory!
