### ISSUE TITLE
Support Yarn's `--exclude`

### ISSUE THREAD

**Issue by sargunv** [IBM/audit-ci#298]
[Certain dependencies](https://github.com/yarnpkg/berry/issues/4117#issuecomment-1371521659) will cause NPM's quick audit endpoint to return a 400 Bad Request error, which bubbles up to `yarn npm audit` failing with that error and `audit-ci` failing with an "Invalid JSON" error.

Normally, we can work around this with `yarn npm audit --exclude <pkg>`, but currently there's no way to pass such excludes to Yarn when running it with `audit-ci`.

Would an "exclude" feature in audit-ci be acceptable? If so, I can start working on a PR.

<img width="825" alt="CleanShot 2023-01-04 at 13 51 14@2x" src="https://user-images.githubusercontent.com/1320357/210656897-f2d70a22-c62f-4315-9a90-a5c1ec39ed68.png">
<img width="859" alt="CleanShot 2023-01-04 at 13 54 37@2x" src="https://user-images.githubusercontent.com/1320357/210657239-74a4c786-cfbc-4470-955f-83755613661f.png">

**Comment by quinnturner** [comment]
I was not aware of this. Absolutely, I would support passing this argument.

One point of debate is whether we should just go ahead and have some approach of passing in extra arguments directly to auditors vs. making an --exclude flag.

**Comment by sargunv** [comment]
> One point of debate is whether we should just go ahead and have some approach of passing in extra arguments directly to auditors vs. making an --exclude flag.

This sounds like a good idea to me
