### ISSUE TITLE
Tests should include all major Yarn versions

### ISSUE THREAD

**Issue by sargunv** [IBM/audit-ci#302]
Currently the tests include Yarn v1 and v2. They should also include v3, and perhaps v4 rc builds?

Since v2 and later (Berry) are all very similar, potentially refactor the test code to reuse the same tests for all major Berry versions.

**Comment by arcanis** [comment]
Note that someone mentioned a bug when used with the 4.0: https://github.com/yarnpkg/berry/issues/5781#issuecomment-1755344002 (we rewrote the command to use a different npm endpoint, which unfortunately doesn't return the same data).

**Comment by quinnturner** [comment]
I have added test cases for Yarn v2 and v3 in `audit-ci`'s latest v7 release. We currently do not support Yarn v4, as documented in my comment here: https://github.com/IBM/audit-ci/issues/332#issuecomment-2143534686.

If you wish to support Yarn v4 and have solid use-cases, please let me know by commenting on that thread!
