### ISSUE TITLE
The audit report format changed?

### ISSUE THREAD

**Issue by alexanderameye** [IBM/audit-ci#318]
CLI and config give different result. When using the package like this

 npx audit-ci --config ./audit-ci.jsonc
 
 I get the following output when using the following config

 ```
{
    "$schema": "https://github.com/IBM/audit-ci/raw/main/docs/schema.json",
    "high": true,
    "allowlist": [],
    "report-type":"full",
    "skip-dev":true,
    "output-format":"json"
}
 ```
 
 ```
{
  "auditReportVersion": 2,
  "vulnerabilities": {
    "react-scripts": {
      "name": "react-scripts",
      "severity": "high",
      "isDirect": true,
      "via": [
        "@svgr/webpack"
      ],
      "effects": [],
      "range": ">=2.1.4",
      "nodes": [
        "node_modules/react-scripts"
      ],
      "fixAvailable": {
        "name": "react-scripts",
        "version": "2.1.3",
        "isSemVerMajor": true
      }
    },
  },
  "metadata": {
    "vulnerabilities": {
      "info": 0,
      "low": 0,
      "moderate": 0,
      "high": 6,
      "critical": 0,
      "total": 6
    },
    "dependencies": {
      "prod": 1456,
      "dev": 0,
      "optional": 2,
      "peer": 7,
      "peerOptional": 0,
      "total": 1464
    }
  }
}
```

However when I use the CLI like this `npx audit-ci --high --output-format json --skip-dev` I get the following result.

```
{
  "advisories": {
    "@svgr/plugin-svgo": {
      "name": "@svgr/plugin-svgo",
      "severity": "high",
      "isDirect": false,
      "via": [
        "svgo"
      ],
      "effects": [
        "@svgr/webpack"
      ],
      "range": "<=5.5.0",
      "nodes": [
        "node_modules/@svgr/plugin-svgo"
      ],
      "fixAvailable": {
        "name": "react-scripts",
        "version": "2.1.3",
        "isSemVerMajor": true
      }
    },
  },
  "metadata": {
    "vulnerabilities": {
      "info": 0,
      "low": 0,
      "moderate": 0,
      "high": 6,
      "critical": 0,
      "total": 6
    },
    "dependencies": {
      "prod": 1456,
      "dev": 0,
      "optional": 2,
      "peer": 7,
      "peerOptional": 0,
      "total": 1464
    }
  }
}
```

So my question is, why is sometimes the json output with a list **vulnerabilities** and why is it sometimes with a list **advisories**?

**Comment by quinnturner** [comment]
It depends on what package manager you are using. I understand it's probably not ideal, but there are four different ways package managers return audits. Rather than trying to consolidate them into one format, audit-ci pipes the response from the original audit of the package manager and publishes it with some minor tweaks.

I assume that you bumped from and old NPM to a newer NPM (or an old Node to a newer Node)?

**Comment by alexanderameye** [comment]
> It depends on what package manager you are using. I understand it's probably not ideal, but there are four different ways package managers return audits. Rather than trying to consolidate them into one format, audit-ci pipes the response from the original audit of the package manager and publishes it with some minor tweaks.
> 
> I assume that you bumped from and old NPM to a newer NPM (or an old Node to a newer Node)?

That makes sense! I thought that audit-ci decided on the output of the report but I'll then investigate what has changed in terms of NPM/Node versions. Thanks :)
