### ISSUE TITLE
v7 ignores command line arguments

### ISSUE THREAD

**Issue by hwo411** [IBM/audit-ci#334]
After updating to v7 command line arguments are ignored

e.g.,

`npx audit-ci@^7 --help`
`audit-ci --help`

and any others perform scan and return results, e.g.

```
Yarn audit report results:
{
  "vulnerabilities": {
    "info": 0,
    "low": 0,
    "moderate": 2,
    "high": 2,
    "critical": 0
  },
  "dependencies": 1666,
  "devDependencies": 0,
  "optionalDependencies": 0,
  "totalDependencies": 1666
}
```

That happen with any argument, e.g., including config.

OS: MacOS 14.5 @ ARM
Node: v18.19.1

That also happens inside docker images.

Version 6 works properly on the same machine.

**Comment by quinnturner** [comment]
Confirmed reproduction, working on it.
