### ISSUE TITLE
Add support for whitelisting specific advisories

### ISSUE THREAD

**Issue by davewasmer** [IBM/audit-ci#37]
It would be nice to be able to whitelist specific advisories (by their `id`, `cve`, or other unique identifier).

For example, I got a `critical` advisory for the `open` package, but I feel safe whitelisting _that specific advisory_ (since it's just a warning about injection attacks via unsanitized user input). But if `open` was hijacked and running malicious code, I wouldn't want to ignore that. But right now, my only option is totally ignore all advisories for that package.

**Comment by quinnturner** [comment]
I agree, this would be a great feature. I will look into doing this tonight!

**Comment by quinnturner** [comment]
@davewasmer I have created #38, does it satisfy your needs? I went with the `id` instead of `cve` for now as it was the easiest implementation and usage pattern.

**Comment by quinnturner** [comment]
Closing as complete with #38
