### ISSUE TITLE
Add ability to specify --registry=https://registry.npmjs.org

### ISSUE THREAD

**Issue by memelet** [IBM/audit-ci#46]
When using a private repo like nexus that does not response correctly to audit, its necessary to use --registry=https://registry.npmjs.org.

**Comment by quinnturner** [comment]
Hi @memelet, thanks for outlining this! I have created #47; you're welcome to review it.

**Comment by memelet** [comment]
Looks perfect. Thanks!

**Comment by quinnturner** [comment]
Closed with the merge of #47
