### ISSUE TITLE
Option to only output a summary report

### ISSUE THREAD

**Issue by dubbha** [IBM/audit-ci#58]
First of all, thank for the effort, I was playing with my own npm package for the CI-friendly yarn audit wrapper before I've found this one, which is very nice and mature.

What I am currently missing is an option to only include a summary report (JSON or not).

I've faced the following when running `audit-ci -c` (only fail on criticals). On the one hand having no report at all seems insufficient (we might have hundreds on major issues, but see nothing, just the successful pass):
```
$ audit-ci -c --report false
Passed yarn security audit.
```
On the other hand in the same situation the output JSON is too huge, particularly going way over the GitLab CI job log limitation:
```
$ audit-ci -c
Yarn audit report JSON-lines:
{
  "type": "auditAdvisory",
  "data": {
    "resolution": {
      "id": 786,
      "path": "ts-jest>cpx>chokidar>anymatch>micromatch>braces",
      "dev": false,
      "optional": false,
      "bundled": false
    },

    ... SO MANY LINES ...

      "jest>jest-cli>jest-runner>jest-config>babel-jest>babel-plugin-istanbul>istanbul-lib-instrument>babel-template>babel-traverse>lodash",
      "jest>jest-cli>jest-runner>jest-config>babel-jest>babel-plugin-istanbul>istanbul-lib-instrument>babel-template>babel-types>lodash",
      "jest>jest-cli>jest-runner>jest-con
Job's log exceeded limit of 4194304 bytes.
```

Having a summary JSON only like the part below would be optimal in this case:

```js
{
  "type": "auditSummary",
  "data": {
    "vulnerabilities": {
      "info": 0,
      "low": 9,
      "moderate": 213,
      "high": 4,
      "critical": 0
    },
    "dependencies": 70026,
    "devDependencies": 0,
    "optionalDependencies": 0,
    "totalDependencies": 70026
  }
}
Passed yarn security audit.
```

We could either extend `--report` to support `full`, `summary`, `none` (as opposed to current boolean).
Or add another option like `--summary`, `-s`.

**Comment by dubbha** [comment]
Could be something like https://github.com/IBM/audit-ci/pull/59 (which only supports yarn). I don't insist though, it's dirty, and only supports yarn for now.

**Comment by dubbha** [comment]
MR #59 updated. Now supports summary output for both - yarn and npm.

**Comment by quinnturner** [comment]
I really like this. I will be reviewing shortly!

**Comment by quinnturner** [comment]
Closing with #59
