### ISSUE TITLE
Remove whitelisted module from JSON output

### ISSUE THREAD

**Issue by glennlegend** [IBM/audit-ci#93]
It would be nice if the output JSON didn't show information about the whitelisted module, or potentially introduce a new report type. It is a bit cumbersome to go through the JSON of vulnerabilities to find a newly introduced vulnerability when the output also contains the module that you have already "ignored". To reduce this noise we are using the summary report type, but that doesn't print out the failing module when a new vulnerability has been introduced.

If we can come up with a resolution to this I'm happy to create a PR!

**Comment by quinnturner** [comment]
I 100% agree with your suggestion and suggest revising the current behaviour of the default report type (`important`) in `v2.x`.

**Comment by quinnturner** [comment]
In `npm-auditer.js`, something like

```js
      const relevantAdvisories = Object.keys(parsedOutput.advisories).reduce(
        (acc, advisory) =>
          levels[parsedOutput.advisories[advisory].severity]
            ? Object.assign(
                { [advisory]: parsedOutput.advisories[advisory] },
                acc
              )
            : acc,
        {}
      );
```

Would be replaced with additional conditions for whether it is whitelisted either by the `whitelist` or `advisories` args.

The same would hold true for `yarn-auditer.js`.
