### ISSUE TITLE
"-bash: audit-ci: command not found" on CircleCI

### ISSUE THREAD

**Issue by joshhogg** [IBM/audit-ci#94]
Running a CircleCI job in version 2 of CircleCi. Have the two commands, slightly modified from the Readme:

```
    - run: cd app && npm install --no-audit
    - run: cd app && audit-ci --moderate
```

When CircleCI executes the command it returns: "/bin/bash: audit-ci: command not found"

We are running node v10.15 and npm v6.9.

What am I missing? From what I understand the code makes a bash script available as audit-ci?

**Comment by quinnturner** [comment]
Hi Josh, sorry for the late response!

I am not sure exactly the issue here. We have a file `bin/audit-ci` that should be picked up within the environment.

One attempt might be `cd app && npm install --no-audit && audit-ci --moderate`? I don't know how that would be any different, just an attempt.

**Comment by dw2** [comment]
We had to install audit-ci globally in our Circle builds for it to work. Have you tried the “-g” flag?
